2017-05-25 14:15:32,923 - INFO - [Elapsed time: 0.03] Creating history AutoSNVPhyl_25-05-2017
2017-05-25 14:15:32,957 - INFO - [Elapsed time: 0.07] [Error Dump]
Traceback (most recent call last):
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 50, in run
    return self.main()  # Return the path to the results zip
  File "/home/devon/PycharmProjects/auto-SNVPhyl/main.py", line 63, in main
    self.history_id = self.gi.histories.create_history(self.NAME)['id']
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/histories/__init__.py", line 34, in create_history
    return Client._post(self, payload)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/client.py", line 157, in _post
    files_attached=files_attached)
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxyclient.py", line 134, in make_post_request
    body=r.text, status_code=r.status_code)
bioblend.ConnectionError: Unexpected HTTP status code: 403: {"err_msg": "Provided API key is not valid.", "err_code": 403001}

